name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint com pylint
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint
